env:
  env_name: "Lift"
  horizon: 100
  use_object_obs: false
  use_camera_obs: True
  camera_height: 128
  camera_width: 128
  has_renderer: false
  has_offscreen_renderer: false
  reward_shaping: true

alg:
  alg_name: "SAC"
  batch_size: 256
  policy: "CnnPolicy"

train:
  exp_name: "sac_cobs_Lift"
  n_envs: 16
  total_timesteps: 10_000_000
  result_save_path: "./results/"

test:
  model_path: "./results/sac_cobs_Lift/best_model/best_model.zip" # Make sure this path matches the saved model path
  n_episodes: 5
  deterministic: true
  save_video: true
  result_save_path: "./results/sac_cobs_Lift/best_model/test/"