env:
  env_name: "Lift"
  use_object_obs: true
  use_camera_obs: false
  has_renderer: false
  has_offscreen_renderer: false
  reward_shaping: true

alg:
  alg_name: "SAC"
  batch_size: 256
  policy: "MlpPolicy"

train:
  exp_name: "sac_oobs_Lift"
  n_envs: 8
  total_timesteps: 5_000_000
  result_save_path: "./results/"

test:
  model_path: "./results/sac_oobs_Lift/best_model/best_model.zip" # Make sure this path matches the saved model path
  n_episodes: 5
  deterministic: true
  save_video: true
  result_save_path: "./results/sac_oobs_Lift/best_model/test/"