env:
  env_name: "PickPlaceCan"
  robots: ["Panda"]
  horizon: 200
  camera_height: 64
  camera_width: 64

alg:
  learning_rate: 0.0003
  n_steps: 512
  batch_size: 32

train:
  n_envs: 8
  device: "cpu"
  total_timesteps: 500000
  save_freq: 10000
  eval_freq: 5000

test:
  model_path: "./models/PPO_pickplace_final.zip"
  n_episodes: 5
  deterministic: true
  save_video: true
  result_path: "./videos/"
  video_fps: 20
  device: "cpu"