env:
  env_name: "PickPlaceCan"
  robots: ["Panda"]
  horizon: 100
  camera_height: 64
  camera_width: 64

alg:
  learning_rate: 0.0003
  n_steps: 256
  batch_size: 64

train:
  n_envs: 16
  device: "cuda"
  total_timesteps: 500000
  save_freq: 20000
  eval_freq: 10000