env:
  env_name: "PickPlaceCan"
  robots: ["Panda"]
  horizon: 200
  camera_height: 128
  camera_width: 128

alg:
  learning_rate: 0.0003
  n_steps: 512
  batch_size: 64

train:
  n_envs: 8
  device: "cuda"
  total_timesteps: 1000000
  save_freq: 10000
  eval_freq: 5000