env:
  horizon: 100
  use_object_obs: true
  use_camera_obs: false
  has_renderer: false
  has_offscreen_renderer: false

alg:
  policy: "MlpPolicy"
  n_steps: 128

train:
  n_envs: 2
  device: "cuda"
  total_timesteps: 1024
  save_freq: 200
  eval_freq: 100
  model_save_path: "./results/test_state/"
  
test:
  model_path: "./results/test_state/best_model/best_model.zip" # Make sure this path matches the saved model path
  n_episodes: 5
  deterministic: true
  save_video: true
  result_path: "./results/test_state/test/"